### ISSUE TITLE
Is it recommended to use @babel/parse or @putout/babel?

### ISSUE THREAD

**Issue by orest22** [putoutjs/printer#2]
- **Version** (`npm -v`): 9.6.4
- **Node Version** `node -v`: 20.1.0
- **OS** (`uname -a` on Linux): Mac
- **Browser name/version**: N/A
- **Used Command Line Parameters**: N/A

Hey, in the [Example](https://github.com/putoutjs/printer?tab=readme-ov-file#example) section you recommend using `@babel/parser` however I faced some issues, for example when printing code like this:

```ts
type test = {
fn: () => void
}
```

**Output:**

```ts
type test = {
fn: () => 
}
```

**Note:** No `void` keyword printed.

It took me some time to figure out what's going on, only after looking at your tests I realized that you are using `@putout/babel`.  Not sure whether it's a bug or just README has to be tweaked.

**Comment by coderaiser** [comment]
Recommended way is using [`@putout/babel`](https://github.com/putoutjs/babel/blob/master/README.md), this is Babel 8 bundled to CommonJS

**Comment by coderaiser** [comment]
Is it works for you?

**Comment by orest22** [comment]
@coderaiser Yes, it worked out 👍
