### ISSUE TITLE
StringLiteral visitor `raw` always undefined

### ISSUE THREAD

**Issue by orest22** [putoutjs/printer#3]
- **Version** (`npm -v`): 9.6.4
- **Node Version** `node -v`: 20.1.0
- **OS** (`uname -a` on Linux): Mac OS
- **Browser name/version**: N/A
- **Used Command Line Parameters**: N/A

Hey, it looks like the [StringLiteral](https://github.com/putoutjs/printer/blob/master/lib/tokenize/literals/index.js#L53) is reading `raw` from the wrong place? It should be `extra.raw` right?

**Comment by coderaiser** [comment]
No, for simplicity `raw` is set on the top of a node similar to the way how it works in ESTree. With help of [estree-to-babel](https://github.com/coderaiser/estree-to-babel)

**Comment by orest22** [comment]
Hmm, make sense, maybe it's documentation problem. I am just using the example you provide and I faced an issue with this kind of code `const = "Tes't"`. Produces `const='Test't'`.

**Comment by coderaiser** [comment]
You need to update options for this purpose:

```js
const ast = parse('const = "Tes't"');

print(ast, {
    format: {
        quote: `"`,
    },
    semantics: {
        encodeSingleQuote: false,
    },
});
```

Is it works for you?

**Comment by orest22** [comment]
@coderaiser It started working right the way when I added `estree-to-babel` for ast. It did confused me a little bit because I used `@putout/babel` to parse the code so the output should be babel ast and then I use `estree-to-babel` to make it compatible with `@putout/printer`.

```
print(ast, {
    format: {
        quote: `"`,
    },
    semantics: {
        encodeSingleQuote: false,
    },
});
```

This would not work for me because I would like to preserve the quote type that is used in the original code to reduce the diff noise when transforming large chunk of code. Majority of the code does use single quotes and only in few cases when string includes single quote instead of escaping it people just wrap their strings with double quotes.

Here is demo: https://stackblitz.com/edit/stackblitz-starters-rl7lpt?file=index.js

**Comment by coderaiser** [comment]
You better use `parse` from 🐊**Putout** :

```js
const {parse} = require('putout');
```

There is no such thing as preserving original chunks of code, anyways you can use [`recast`](https://github.com/coderaiser/putout#printer) option for transforming with 🐊**Putout**, it is not maintained and much slower, but it tries to preserve code style.
