### ISSUE TITLE
Wrong convert if use space:''

### ISSUE THREAD

**Issue by sirenkovladd** [putoutjs/printer#4]
```js
import {parse} from 'putout';
import {print} from '@putout/printer';
const js = `function c(n) {return (s)=>s.b*n}`;

const ast = parse(js);
const code = print(ast, {
    format: {
        space: '',
        roundBraceOpen: '',
        roundBraceClose: '',
    },
});

console.log(code);
```

result
```sh
❯ node t.js
function c(n){
    returns=>s.b*n;
}
```

expect
```
❯ node t.js
function c(n){
    return s=>s.b*n;
}
```

https://github.com/putoutjs/minify/blob/master/lib/minify.js#L28-L41

I don't understand why, but node considers this syntax valid
and the result of this function is undefined and not a callback
upd: returns is parameter of arrow function

**Comment by coderaiser** [comment]
Thanks! [Just fixed](https://github.com/putoutjs/printer/releases/tag/v8.0.0) 🎉 . 
Now API looks this way:

```js
const code = print(ast, {
    format: {
        space: '',
    },
    semantics: {
        roundBraces: false,
    }
});
```

Is it works for you?

**Comment by sirenkovladd** [comment]
Yes, thank you so much)
